Fixed bugs and lint errors.
topcoder-platform/micro-frontends-taas-admin-app pull request #3
Opened 2021-05-29 13:02 UTC by MadOPcode

2021-05-29 13:23 UTC, maxceem requested changes
Thank you @MadOPcode.

All the issue looks fixed, there is just a couple of question regarding the code, could you please have a look below:

2021-05-29 13:23 UTC, maxceem commented on src/routes/WorkPeriods/components/PeriodFilters/index.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
it's preferable not to disable rules. Is there any reason for disabling it, or we can list dependencies here and in all other similar places?

2021-05-29 13:23 UTC, maxceem commented on src/root.component.jsx
> +    document.documentElement.classList.add("taas-admin");
In general, it's preferable not to use global classes and only use CSS Modules. What do we need this class for? Can we avoid adding it?

2021-05-29 13:40 UTC, MadOPcode commented on src/routes/WorkPeriods/components/PeriodFilters/index.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
It's okay to add dispatch to the hook's dependencies. But since the identity of Redux's dispatch function returned by useDispatch is stable between re-renders (provided the store passed to <Provider> is not changed) I thought that it's okay to omit it from dependencies and disable this rule for such cases.

2021-05-29 13:49 UTC, MadOPcode commented on src/root.component.jsx
> +    document.documentElement.classList.add("taas-admin");
This class is used for scoping CSS styles for html, body and some other elements inside the <Root> component of TaaS Admin App. Specifically it facilitates the styling of sidebar's and content area's layout. Instead of global class name the class name from CSS module can be used. But this class name should not be removed. Otherwise the layout will break.

2021-05-29 14:47 UTC, maxceem commented on src/root.component.jsx
> +    document.documentElement.classList.add("taas-admin");
Inside the [Earn app](https://platform.topcoder-dev.com/earn) the same layout is implemented without using global style for `html` see 

![image](https://user-images.githubusercontent.com/146016/120074428-8ea13b00-c0a5-11eb-8bae-511e57ba6eda.png)

The reason why I'd like to avoid it is because we are using MFE architecture and it's better not to make any changes into the common elements like `html`, `body` and so on.

We should only change styles inside the TaaS Admin App container `single-spa-application:@topcoder/micro-frontends-taas-admin-app`:

![image](https://user-images.githubusercontent.com/146016/120074522-e475e300-c0a5-11eb-8503-ecb91ba8ea20.png)

2021-05-29 14:49 UTC, maxceem commented on src/routes/WorkPeriods/components/PeriodFilters/index.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Let's just add the dependency to the hooks. It's better to be consistent: we should either follow the rule or disable it for all the cases. As this is a good rule, let's just always follow it.

2021-05-29 14:56 UTC, MadOPcode commented on src/routes/WorkPeriods/components/PeriodFilters/index.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Okay. I'll re-enable the rule everywhere and add dependencies to corresponding hooks.

2021-05-29 15:05 UTC, MadOPcode commented on src/root.component.jsx
> +    document.documentElement.classList.add("taas-admin");
Okay. I'll redo the layout without styling external elements.

2021-05-31 11:14 UTC, maxceem approved these changes
Thank you @MadOPcode for taking care of the sidebar for small screens.

2 issues from the list are not fixed:
❌ Use inline SVG plugin instead of creating components manually for SVG files. (let me know if there are any difficulties with it)
❌ It's preferable to not use background SVG, and inline SVG files, this way all the images would be loaded immediately. (let me know if there are any difficulties with it)

But we would make them as a separate PR, as this PR is already has a lot of good fixes.

2021-05-31 11:15 UTC, merged