Adds fixes for adding and editing payments, implements WP data reloading, updates toastr positioning
topcoder-platform/micro-frontends-taas-admin-app pull request #99
Opened 2021-08-14 03:49 UTC by MadOPcode

Adds fixes for #80, #82. Implements #94, #95.

2021-08-14 13:29 UTC, maxceem requested changes
Thank you @MadOPcode most of the things work great. There is a couple of small improvements I'd like to make:

1. The font in the Tooltip for Additional Payment is not the same like in other tooltips, can we make it the same?

     ![image](https://user-images.githubusercontent.com/146016/129447491-0c3e3f2c-a5f3-48e8-bacf-5f77b633e39e.png)
     
     ![image](https://user-images.githubusercontent.com/146016/129447553-85c6ab86-693e-4bb5-80d7-b8ea21c0d194.png)

2. When we edit the payment `days` or `amount`, if we change value and then change back so the value is same before, the "Update" button stays enabled, though it suppose to get disabled again as there is not more changes in the form anymore, see demo video https://monosnap.com/file/3GjLOz79x6cqajFPodzVgcIf8Q4B0f     

And one more thing in code below.

2021-08-14 13:29 UTC, maxceem commented on src/routes/WorkPeriods/components/PeriodActions/index.jsx
> +        checkDisabled() {
Is it possible to make this field `boolean` type and name it something like `disabled` instead of a function? Anyway it's recalculated here every time when `period.start` changed.

2021-08-14 13:29 UTC, maxceem commented on src/routes/WorkPeriods/components/PeriodActions/index.jsx
> +      // @ts-ignore
What is the reason for adding this?

2021-08-14 15:41 UTC, MadOPcode commented on src/routes/WorkPeriods/components/PeriodActions/index.jsx
> +        checkDisabled() {
1. Fixed tooltip font.
2. I somehow thought that the "Update" button was supposed to be disabled only initially before the user touched anything. Updated the behavior of edit-payment modals.
3. Removed handling of `checkDisabled` function in items for ActionsMenu. Now reasons for disabling specific item have to be assigned to the "disabled" property.

2021-08-14 15:57 UTC, MadOPcode commented on src/routes/WorkPeriods/components/PeriodActions/index.jsx
> +      // @ts-ignore
In the type inferred by Typescript parser for the `actions` variable's items the "checkDisabled" property was a required property so Typescript parser complained if this property was not present in other items. It could be resolved by defining a useless `checkDisabled` method that would always return `false` for other items or by disabling type-checking by Typescript parser with this comment.

2021-08-16 07:49 UTC, maxceem approved these changes
@MadOPcode thanks, all works good as per local testing. Passing it for QA.

2021-08-16 07:49 UTC, merged